### PR TITLE
Directive for dynamic <title>

### PR DESCRIPTION
**Pull request by arsylum**
This addresses #84

An attribute directive for the `<title>` element that listens to `$routeChangeStart` on `$rootScope` and generates a new title every time.

This approach actually takes away from the modularity since declaring titles for pages is something that should be handled by the module that contains those pages. Then again it's an edge case and having it in one place is also convenient.

The `<body>` element's sqid-app directive had to be moved one level down in a wrapping div, otherwise there was a special race condition when refreshing a page with remotely retrieved labels in title:
1. squidTitle directive makes an wikidataapi ajax call, so angular appends a `<script>` node to the body 
2. squidApp directive replaces contents of `<body>`
3. when the callback for the request fires, angular tries to remove the `<script>` node that is no longer there, causing a JS error.
(that was a mean one to figure out...)

### CODE REVIEW

**Comment by mkroetzsch** [comment]
I am afraid that there is still some race condition here. Two ways to reproduce:
1. "Empty cache and hard reload" from any view page
2. Open a link to a View in a new tab.
In either case, I get a page that is entitled "PAGE_TITLE.VIEW: <label> - SQID"

**Comment by arsylum** [comment]
for some reason I cannot reproduce this (in chromium). For me in both cases it consistently shows 'SQID - Wikidata Explorer` at first and after a short delay changes to the desired page title. Which setup is causing the described behavior?

**Comment by mkroetzsch** [comment]
I am also using Chromium, but I have sent the language to German using lang=de. Then I open a link in a new tab. It seems that it is working in English for me too (with a similar delay as you mention).

**Comment by arsylum** [comment]
I can confirm this is broken with any other language than en. It is *very* confusing to me though. Observations so far:

1. The `$translate('IDENTIFIER')` resolves returning the string specified in `en.json` for that `IDENTIFIER` when the language in use is `en`.
2. With any other language the promise rejects and returns the `IDENTIFIER` string, irregardles of that `IDENTIFIER` being present in that languages json or not.
3. `$translate.isReady` equals `false` on the first time the directive logic is run within a fresh page load (refresh). (But that's why it uses Promises, right?)
4. Trying to make use of [`$translate.onReady()`](https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translate#methods_onready) doesn't help.
5. Yet it definitely is a race condition problem, since i.e. delaying the execution by a timeout of 2000 generally prevents the problem. Of course this is not an acceptable solution.
6. `en.json` apparently is always requested before any other language json file (I assume because it's specified as fallback).

It's driving me a little bit nuts at the moment. Maybe I should revisit after some coffee...

**Comment by arsylum** [comment]
Ok this has gotten too cumbersome so I did a slightly hackish but simple workaround. The page name translation part of the directive is now kept in a timeout loop until `$translate.isReady()` returns true. 

The `SQID - Wikidata Explorer` that shows up initially is from the `index.html`s `title` tag (before angular takes over control). It could be reasonable to change it to an empty string or maybe 'SQID loading...` or something. I still left it because I wanted to retain some descriptiveness in the static markup, but there is not so much left of that anyway..

**Comment by mkroetzsch** [comment]
This branch now reports conflicts, but I guess they cannot be large, since no big merges have happened recently.

**Comment by mkroetzsch** [comment]
I have tried to simplify the title definitions a but further, removing "custom" and just using the page instead (I also removed the "View" prefix to this part). Unfortunately, it does not work reliably for me. I am on a very slow connection with significant lag, and I observe the following behaviours in lang=de when using the View view:

1. After a short delay where the default title is shown, the title is set to the correct label. This is how it should be.
2. The default title is shown but there is no label even after considerable time of waiting. Maybe this could be a timeout, but if it happens I cannot fix it by reloading.
3. The default title is shown briefly, but then after a short moment, the Qid is shown instead of the label, even though a label does exist for de and is correctly shown in the page.

In all cases, the page renders as expected with all labels shown. I wonder if the errors are related to my simplifications or if there is a problem that only shows when on a very slow connection.

**Comment by mkroetzsch** [comment]
Ok, after some more testing, I am convinced that it works well enough for now. The errors are quite spurious even on my slow connection.

**Comment by mkroetzsch** [comment]
I realized now why the label fetching in the title works very well in normal browsing: when you click on any link, it usually shows the label, so it is already cached and needs not be fetched at all.

**Pull request merged**
